### ISSUE TITLE
Increasing the size of the figure legend

### ISSUE THREAD

**Issue by pbkeating** [reconhub/epicontacts#103]
Hi,

Wondering if it would be possible to increase the size of the legend on the double axis plot?
When presenting on powerpoint slides, the legend doesn't come across well.

<img width="79" alt="legend_epicontacts" src="https://user-images.githubusercontent.com/20238915/57886539-b78f6400-782d-11e9-81cf-6affc71dcc53.PNG">

**Comment by finlaycampbell** [comment]
Hi Pat.
Here's a solution by manipulating the plot object `p` directly:
```
p$x$legend$width <- 0.2
p$x$legend$nodes$font.size <- 25
```
At some point we'll have to decide how many of these visNetwork options we want to include as arguments within epicontacts, I think for now I'll just keep adding examples to the vignette!

**Comment by zkamvar** [comment]
> At some point we'll have to decide how many of these visNetwork options we want to include as arguments within epicontacts, I think for now I'll just keep adding examples to the vignette!

It's always a struggle to specify what to add in a visualisation, especially one that wraps another visualisation tool :grimacing:. 

It may be worth further splitting things out into user-facing functions. like we could split out the legend addition into a separate function so that it's easier for users to customise (though that may be better added to visNetwork itself)
