### ISSUE TITLE
Potential bug in `subset_clusters_by_id`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#45]
In the example code, the resulting object does not show the "target case" in the plot:

```r
 ## build data
     x <- make_epi_contacts(ebola.sim$linelist, ebola.sim$contacts,
                            id="case.id", to="case.id", from="infector",
                            directed=TRUE)
     
     
     id <- "cac51e" ## it can be a vector of id as well
     
     
     ## subset based on cluster to which "cac51e" belongs
     x_subset <- subset_clusters_by_id(x, id)

     plot(x_subset) # does not show `cac51e`
```

**Comment by nistara** [comment]
That's because "cac51e" is in the contacts dataframe, but not in the linelist. Should I subset the clusters such that only those nodes that appear in the linelist as well are included?

**Comment by thibautjombart** [comment]
I am not sure I understand, sorry. It seems to me that clusters are connected components of the graph, so that they should be defined for all nodes of the graph. Cases that were not otherwise documented should still have a cluster membership. But I'm sleep deprived and over-caffeinated, so tell me if I miss something ;)

**Comment by finlaycampbell** [comment]
I think the issue here is that the plot function only takes individuals from the linelist as nodes - individuals that are found only in the contact dataframe (such as "cac51e") are not defined as nodes in the visNetwork object, and therefore aren't plotted (they are only fed into the visNetwork object through the edges dataframe - however these edges aren't plotted, because visNetwork only plots edges if both nodes are provided in the nodes dataframe). Here's a suggested way of fixing the problem:

In the vis_epi_contacts function, currently the nodes are fed in this way:

`   nodes <- x$linelist
    nodes$label <- nodes$id
    nodes$group <- as.character(nodes[,group])
    nodes$group[is.na(nodes$group)] <- "NA"
    nodes$group <- factor(nodes$group)`

If we instead draw the nodes from both the linelist and contacts dataframe:

`    ## make visNetwork inputs: nodes
    nodes <- data.frame(id=unique(c(x$linelist$id,x$contacts$from,x$contacts$to)))
    nodes$label <- nodes$id
    nodes$group <- as.character(nodes[,group])
    nodes$group[is.na(nodes$group)] <- "NA"
    nodes$group <- factor(nodes$group)`

This results in the "cac51e" individual being plotted. 
![image](https://cloud.githubusercontent.com/assets/18398011/19600610/be779990-979d-11e6-8616-30f7159bac1e.png)

I don't know if we want to include this - the drawback of this approach is that individuals drawn from the contacts dataframe don't have any node attributes (ie. outcome, hospital, gender, etc.) - if we want to colour nodes by these attributes, we would have to introduce a "NA" colour.

**Comment by finlaycampbell** [comment]
Looks the code didn't print very clearly. The difference is:
`nodes <- x$linelist`

vs. 

`nodes <- data.frame(id=unique(c(x$linelist$id,x$contacts$from,x$contacts$to)))`

**Comment by finlaycampbell** [comment]
Updated the node definition, so all individuals subsetted by id should be plotted now

**Comment by nistara** [comment]
Thanks Finley!
