### ISSUE TITLE
small bug in `get_clusters`: cases not in linelist

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#65]
`get_clusters` is cool =D

I was just adding a new example in the vignette for it. There's a weird thing happening, with invidiuals in some clusters effectively having no cluster:

```
x <- make_epicontacts(ebola_sim$linelist, ebola_sim$contacts,
                      id = "case.id", to = "case.id", from = "infector",
                      directed = TRUE)
x
x <- get_clusters(x)
x_14 <- subset(x, cs = 14)
plot(x_14, "cluster_member")

```
See the nodes in grey on the plot. I think it comes from the fact that these nodes are in `x$contacts` but not in the `x$linelist` before the call to `get_clusters`. When calling `get_clusters(x, output = "epicontact")` (the default) we may want to add automatically entries in the `$linelist` (with their ID and cluster info, and NA elsewhere). 

Incidentally, this may be a more general task to implement in a function - like the opposite of `thin`. `fatten`? 
@nistara  @vpnagraj what do you think?

**Comment by nistara** [comment]
Fixed it!

It was originally written to return an `epicontacts` object similar to what was entered, with just the cluster info added. Now it adds all the entries originally present in the `contacts` but not in the `linelist` to the new `linelist` (or dataframe, if we choose that as the output instead of an `epicontacts` object). 

We might want to add this to the documentation also, right? So users aren't surprised that their `epicontacts` object changed a bit?

**Comment by thibautjombart** [comment]
Awesome! Yes I think you're right, it would be good to add to the doc, maybe in the `@return` or `@details` bit.
